@startuml
!define LIGHTBLUE
'!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

'__Title
title
PERSONAL FINANCE MANAGEMENT

<u>GroupDTOAssembler</u>  Sequence Diagram

end title

hide footbox

participant "groupDTOAssembler : GroupDTOAssembler"
activate "groupDTOAssembler : GroupDTOAssembler" #34b7eb
"groupDTOAssembler : GroupDTOAssembler" [#blue]--> "createGroupDTO : CreateGroupDTO" **: createDTOFromDomainObject (denomination, description, dateOfCreation)
                    return <b>createGroupDTO</b>

@enduml