@startuml
!define LIGHTBLUE
'!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

'__Title
title
PERSONAL FINANCE MANAGEMENT

<u>DateOfCreation</u>  Sequence Diagram

end title

hide footbox

participant "DateOfCreation"
                    activate "DateOfCreation" #34b7eb
"DateOfCreation" [#blue]--> "dateOfCreation:DateOfCreation" **: createDateOfCreationAutomatic()
@enduml