@startuml
!define LIGHTBLUE
'!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

'__Title
title
PERSONAL FINANCE MANAGEMENT

<u>GroupID</u>  Sequence Diagram

end title

hide footbox

participant "GroupID"
                    activate "GroupID" #34b7eb
"GroupID" [#blue]--> "groupID:GroupID" **: createGroupID (groupDenomination)

@enduml